---
ci:
    collect:
        startServerCommand: npm run start
        startServerReadyPattern: Ready in
        url:
            - http://localhost:3000/en/home
            - http://localhost:3000/en/view/Wohnberechtigte-Bevölkerung-1
            - http://localhost:3000/en/view/Points-of-Interest-Kinos-3
        numberOfRuns: 1
        settings:
            preset: desktop
    assert:
        preset: lighthouse:recommended
    upload:
        target: temporary-public-storage
