---
ci:
    collect:
        startServerCommand: npm run start
        startServerReadyPattern: Ready in
        url:
            - http://localhost:3000/en/home
            - http://localhost:3000/en/dashboard/bevölkerung-1
            - http://localhost:3000/en/dashboard/verkehr-und-infrastruktur-2
            - http://localhost:3000/en/dashboard/kultur-und-öffentliches-leben-3
            - http://localhost:3000/en/dashboard/freizeitangebote-4
            - http://localhost:3000/en/dashboard/für-zugezogene-5
            - http://localhost:3000/en/dashboard/für-studierende-6
            - http://localhost:3000/en/overview/resources
            - http://localhost:3000/en/overview/dashboards
            - http://localhost:3000/en/dashboard/bevölkerung-1
            - http://localhost:3000/en/resource/wohnberechtigte-bevölkerung-71ef348f-0f5b-46a0-8250-e87aae9f91bd
            - http://localhost:3000/en/resource/stadtteile-stadt-karlsruhe-2a7fd644-bc67-477a-bb9e-cf88f076b7af
            - http://localhost:3000/en/legal-notice
        numberOfRuns: 1
        settings:
            preset: desktop
    assert:
        preset: lighthouse:recommended
    upload:
        target: temporary-public-storage
