---
default: true
MD033: false
MD038: false
line-length:
  line_length: 150
  heading_line_length: 80
  code_block_line_length: 80
  code_blocks: true
  tables: true
  headings: true
  strict: false
  stern: false
