site_name: Open Data Dashboard
repo_url: https://github.com/stadt-karlsruhe/open-data-dashboard
theme:
    name: material
    language: en
    features:
        - search.suggest
        - search.highlight
        - search.share
plugins:
    - search
extra:
    version:
        provider: mike
    alternate:
        - name: English
          link: /en/
          lang: en
        - name: Deutsch
          link: /de/
          lang: de
