site_name: Open Data Dashboard
site_url: https://open-data-dashboard.readthedocs.io
repo_url: https://github.com/stadt-karlsruhe/open-data-dashboard
extra_css:
    - stylesheets/extra.css
theme:
    name: material
    language: en
    features:
        - search.suggest
        - search.highlight
        - search.share
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - navigation.sections
        - navigation.indexes
        - navigation.top
        - navigation.path
        - content.code.copy
        - content.code.annotate
    palette:
        primary: custom
nav:
    - Home: index.md
    - About:
          - about/index.md
          - Features:
                - about/visualizations.md
                - about/dashboards.md
          - about/technical-documentation.md
    - Configuration:
          - configuration/index.md
          - Configuration Options:
                - configuration/appearance.md
                - configuration/resources.md
                - configuration/visualizations.md
                - configuration/categories.md
                - configuration/dashboards.md
          - Supported Data: configuration/data-types.md
    - Development: development/index.md
    - CI/CD and Testing:
          - ci-cd/ci.md
          - ci-cd/cd.md
          - ci-cd/testing.md
plugins:
    - search
    - glightbox
    - i18n:
          docs_structure: suffix
          languages:
              - locale: en
                default: true
                name: English
                build: true
              - locale: de
                name: Deutsch
                build: true
    - build_plantuml:
          render: "server"
          server: "https://www.plantuml.com/plantuml"
          output_format: "svg"
          diagram_root: "docs/diagrams"
          output_folder: "out"
          input_folder: "src"
extra:
    alternate:
        - name: English
          link: /
          lang: en
        - name: Deutsch
          link: /de/
          lang: de
markdown_extensions:
    - toc:
          permalink: true
    - admonition
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - attr_list
    - md_in_html
    - tables
