import './globals.css';
import './globals.scss';
import { Metadata } from 'next';
import { ReactNode } from 'react';

interface Props {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Props) {
  return children;
}
