appearance:
    theme: "karlsruhe"

dashboards:
    - id: homepage
      name: Homepage
      icon: house-door-fill
      contents:
          - type: EXTERNAL
            source: https://www.wetter.de/widget/heute/u0tyz1rj/false/
            name: Weather
    - id: "1"
      name: Bevölkerung
      icon: people-fill
    - id: "2"
      name: Bildung
    - id: "3"
      name: Mobilität
      icon: train-front-fill
