appearance:
    theme: "karlsruhe"
resources:
    - id: "1"
      source: https://mocki.io/v1/1442bc5a-869f-4398-96a9-c5c50fc3b1a3
      #   source: https://transparenz.karlsruhe.de/datastore/dump/71ef348f-0f5b-46a0-8250-e87aae9f91bd?format=json
      type: JSON
      name: Wohnberechtigte Bevölkerung
      description: dadad
      renameProperties:
          mannlich (%): Männlich (%)
          weiblich (%): Weiblich (%)
      skipPropertiesRegEx: ^_id$
      defaultFilters:
          Jahr:
              min: 2009
              max: 2009
      visualizations:
          barChart:
              axisPairs:
                  - xAxis: Stadtteil
                    yAxis: Wohnberechtigte
                  - xAxis: Stadtteil
                    yAxis: Hauptwohnung (%)
                  - xAxis: Stadtteil
                    yAxis: Nebenwohnung (%)
          table: {}
    - id: "2"
      source: https://web6.karlsruhe.de/Stadtentwicklung/statistik/pdf/mietspiegel/karlsruher-mietspiegel-2023.pdf
      type: Embedded
      name: Karlsruher Mietspiegel 2023
    - id: "3"
      source: https://mocki.io/v1/56ffb4b7-49d5-4763-98ec-db1a67feb0a5
      # source: https://geoportal.karlsruhe.de/server/rest/services/Stadtplan/Stadtplan_POIs_Kultur/MapServer/3/query?where=GRUPPENNAME_DE+%3D+%27Kinos%27&outFields=NAME%2CGRUPPENNAME_DE%2CUPDATED&returnGeometry=true&f=geojson
      type: GeoJSON
      name: Points of Interest Kinos
      renameProperties:
          NAME: Name
          GRUPPENNAME_DE: Kategorie
      skipPropertiesRegEx: ^UPDATED$
      visualizations:
          map:
              groupKey: Kategorie
    - id: "4"
      source: https://mocki.io/v1/becc7043-0251-46e9-8f2b-81a6b904fe86
      # source: https://transparenz.karlsruhe.de/datastore/dump/e3e69806-4903-44c4-a17d-bce2a940d3a0?format=json
      type: JSON
      name: Wanderungssaldo
      skipPropertiesRegEx: ^_id$
      visualizations:
          barChart:
              axisPairs:
                  - xAxis: Stadtteil
                    yAxis: Personen
          table: {}
    - id: "5"
      source: https://transparenz.karlsruhe.de/datastore/dump/a5f04b45-528a-41b5-8d8c-eb9677bf2fd1?bom=True
      type: CSV
      name: Hunde insgesamt
      skipPropertiesRegEx: ^_id$
      visualizations:
          barChart:
              axisPairs:
                  - xAxis: Stadtteil
                    yAxis: Hunde
          table: {}
    - id: "6"
      source: https://mocki.io/v1/8b010dfa-a1ab-4139-9f84-f213098ec1f1
      # source: https://transparenz.karlsruhe.de/datastore/dump/b97c9405-ecb8-42a8-9854-560d2f921531?format=json
      type: JSON
      name: Europawahl 2019
      numberFormat: de
      visualizations:
          barChart:
              axisPairs:
                  - xAxis: Partei/politische Vereinigung
                    yAxis: Stimmen
                  - xAxis: Parteiname
                    yAxis: "%"
    - id: "7"
      source: https://mocki.io/v1/iprobablydontexist
      # source: https://transparenz.karlsruhe.de/datastore/dump/iprobablydontexist?format=json
      type: JSON
      name: Not Found
      visualizations:
          table: {}
    - id: "8"
      source: https://mocki.io/v1/5e610643-2531-4aba-9191-aa1c2524e96e
      type: JSON
      name: Empty
      visualizations:
          table: {}
