appearance:
    theme: "karlsruhe"
resources:
    - id: "1"
      source: https://transparenz.karlsruhe.de/datastore/dump/71ef348f-0f5b-46a0-8250-e87aae9f91bd?format=json
      type: JSON
      name: Wohnberechtigte Bevölkerung
      description: Die Beschreibung für die Wohnberechtigte Bevölkerung
      category: Gesellschaft
      renameProperties:
          mannlich (%): Männlich (%)
          weiblich (%): Weiblich (%)
      skipPropertiesRegEx: ^_id$
      defaultFilters:
          Jahr:
              min: 2009
              max: 2009
      visualizations:
          barChart:
              axisPairs:
                  - xAxis: Stadtteil
                    yAxis: Wohnberechtigte
                  - xAxis: Stadtteil
                    yAxis: Hauptwohnung (%)
                  - xAxis: Stadtteil
                    yAxis: Nebenwohnung (%)
          table: {}
    - id: "2"
      source: https://web6.karlsruhe.de/Stadtentwicklung/statistik/pdf/mietspiegel/karlsruher-mietspiegel-2023.pdf
      type: PDF
      name: Karlsruher Mietspiegel 2023
      category: Gesellschaft
    - id: "3"
      source: https://geoportal.karlsruhe.de/server/rest/services/Stadtplan/Stadtplan_POIs_Kultur/MapServer/3/query?where=GRUPPENNAME_DE+%3D+%27Kinos%27&outFields=NAME%2CGRUPPENNAME_DE%2CUPDATED&returnGeometry=true&f=geojson
      type: GeoJSON
      name: Points of Interest Kinos
      category: Gesellschaft
      renameProperties:
          NAME: Name
          GRUPPENNAME_DE: Kategorie
      skipPropertiesRegEx: ^UPDATED$
      visualizations:
          map:
              groupKey: Kategorie
    - id: "4"
      source: https://transparenz.karlsruhe.de/datastore/dump/e3e69806-4903-44c4-a17d-bce2a940d3a0?format=json
      type: JSON
      name: Wanderungssaldo
      category: Category 3
      skipPropertiesRegEx: ^_id$
      visualizations:
          barChart:
              axisPairs:
                  - xAxis: Stadtteil
                    yAxis: Personen
          table: {}
    - id: "5"
      source: https://transparenz.karlsruhe.de/datastore/dump/a5f04b45-528a-41b5-8d8c-eb9677bf2fd1?bom=True
      type: CSV
      name: Hunde insgesamt
      category: Mobilität
      skipPropertiesRegEx: ^_id$
      visualizations:
          barChart:
              axisPairs:
                  - xAxis: Stadtteil
                    yAxis: Hunde
          table: {}
    - id: "6"
      source: https://transparenz.karlsruhe.de/datastore/dump/b97c9405-ecb8-42a8-9854-560d2f921531?format=json
      type: JSON
      name: Europawahl 2019
      numberFormat: de
      category: Gesellschaft
      subcategory: Politik
      visualizations:
          barChart:
              axisPairs:
                  - xAxis: Partei/politische Vereinigung
                    yAxis: Stimmen
                  - xAxis: Parteiname
                    yAxis: "%"
    - id: "7"
      source: https://web6.karlsruhe.de/Stadtentwicklung/statistik/mietspiegelrechner/mietspiegel-2023.html
      type: HTML
      name: Mietspiegelrechner
      category: Gesellschaft
categories:
    - name: Mobilität
      description: Eine Kategorie, in der Daten im Bereich Mobilität zusammengefasst werden.
      icon: train-front-fill
    - name: Gesellschaft
      description: Hier sind Daten aus dem Bereich Gesellschaft zusammengefasst.
      icon: people-fill
      subCategories:
          - name: Politik
            description: In dieser Unterkategorie findet man alle politischen Daten.
            icon: award-fill
    - name: Category 3
      description: Die dritte Kategorie.
dashboards:
    - id: homepage
      name: Homepage
      icon: house-door-fill
      contents:
          - type: EXTERNAL
            source: https://www.wetter.de/widget/heute/u0tyz1rj/false/
            name: Weather
    - id: "1"
      name: Bevölkerung
      icon: people-fill
    - id: "2"
      name: Bildung
    - id: "3"
      name: Mobilität
      icon: train-front-fill
